### ISSUE TITLE
How to connect via localhost

### ISSUE THREAD

**Issue by EvanBurbidge** [drginm/docker-boilerplates#1]
When developing I wanna be able to connect to these dbs via a localhost string. 

Any tips on what the string format may look like?

**Comment by drginm** [comment]
Hi @EvanBurbidge , sorry for the delay (I just saw this!)

It depends, given that I am running my containers using Docker Tools for Windows they have a different private IP and won't work using 127.0.0.1 or http:localhost:port.  When I use docker for windows or even for Mac I can use localhost for the containers.

Having said that you could look for the hosts file for you operating system and add a mapping there, so that you can use a "domain", so for example in windows you could add the following line at the end of the c:\Windows\System32\Drivers\etc\hosts file:
192.100.100.100       **mongodb1**

Then on the db string you can use:
const DATABASE_CONECTION = 'mongodb://**mongodb1**/test';

Hope this helps.
